# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ControlCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ControlCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsControlCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ControlCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ControlCommand
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ControlCommand
    def LinearVel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from RobotDataFlow.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ControlCommand
    def AngularVel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from RobotDataFlow.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ControlCommandStart(builder):
    builder.StartObject(3)

def Start(builder):
    ControlCommandStart(builder)

def ControlCommandAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(0, timestamp, 0)

def AddTimestamp(builder, timestamp):
    ControlCommandAddTimestamp(builder, timestamp)

def ControlCommandAddLinearVel(builder, linearVel):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(linearVel), 0)

def AddLinearVel(builder, linearVel):
    ControlCommandAddLinearVel(builder, linearVel)

def ControlCommandAddAngularVel(builder, angularVel):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(angularVel), 0)

def AddAngularVel(builder, angularVel):
    ControlCommandAddAngularVel(builder, angularVel)

def ControlCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return ControlCommandEnd(builder)
