# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# E-Stop 消息：显式建模急停指令，消除 reactor.cpp 中的硬编码字节
class EStop(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EStop()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEStop(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EStop
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EStop
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EStop
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EStopStart(builder):
    builder.StartObject(2)

def Start(builder):
    EStopStart(builder)

def EStopAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(0, timestamp, 0)

def AddTimestamp(builder, timestamp):
    EStopAddTimestamp(builder, timestamp)

def EStopAddReason(builder, reason):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)

def AddReason(builder, reason):
    EStopAddReason(builder, reason)

def EStopEnd(builder):
    return builder.EndObject()

def End(builder):
    return EStopEnd(builder)
