# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RobotMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RobotMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRobotMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RobotMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RobotMessage
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # RobotMessage
    def Seq(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # RobotMessage
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RobotMessage
    def Payload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def RobotMessageStart(builder):
    builder.StartObject(4)

def Start(builder):
    RobotMessageStart(builder)

def RobotMessageAddType(builder, type):
    builder.PrependInt8Slot(0, type, 0)

def AddType(builder, type):
    RobotMessageAddType(builder, type)

def RobotMessageAddSeq(builder, seq):
    builder.PrependUint32Slot(1, seq, 0)

def AddSeq(builder, seq):
    RobotMessageAddSeq(builder, seq)

def RobotMessageAddPayloadType(builder, payloadType):
    builder.PrependUint8Slot(2, payloadType, 0)

def AddPayloadType(builder, payloadType):
    RobotMessageAddPayloadType(builder, payloadType)

def RobotMessageAddPayload(builder, payload):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder, payload):
    RobotMessageAddPayload(builder, payload)

def RobotMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return RobotMessageEnd(builder)
