# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Telemetry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Telemetry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTelemetry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Telemetry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Telemetry
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Telemetry
    def Pos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from RobotDataFlow.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Telemetry
    def Vel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from RobotDataFlow.fbs.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Telemetry
    def BatteryVoltage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Telemetry
    def CpuUsage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def TelemetryStart(builder):
    builder.StartObject(5)

def Start(builder):
    TelemetryStart(builder)

def TelemetryAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(0, timestamp, 0)

def AddTimestamp(builder, timestamp):
    TelemetryAddTimestamp(builder, timestamp)

def TelemetryAddPos(builder, pos):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(pos), 0)

def AddPos(builder, pos):
    TelemetryAddPos(builder, pos)

def TelemetryAddVel(builder, vel):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(vel), 0)

def AddVel(builder, vel):
    TelemetryAddVel(builder, vel)

def TelemetryAddBatteryVoltage(builder, batteryVoltage):
    builder.PrependFloat32Slot(3, batteryVoltage, 0.0)

def AddBatteryVoltage(builder, batteryVoltage):
    TelemetryAddBatteryVoltage(builder, batteryVoltage)

def TelemetryAddCpuUsage(builder, cpuUsage):
    builder.PrependFloat32Slot(4, cpuUsage, 0.0)

def AddCpuUsage(builder, cpuUsage):
    TelemetryAddCpuUsage(builder, cpuUsage)

def TelemetryEnd(builder):
    return builder.EndObject()

def End(builder):
    return TelemetryEnd(builder)
